module.exports = {
  slug: 'bromo',
  title: 'Gunung Bromo',
  image: 'https://images.unsplash.com/photo-1523100647980-c7a39cb1bcfe?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=3300&q=80',
  description: 'Gunung Bromo mempunyai sebuah kawah dengan garis tengah ± 800 meter (utara-selatan) dan ± 600 meter (timur-barat). Sedangkan daerah bahayanya berupa lingkaran dengan jari-jari 4 km dari pusat kawah Bromo.',
  content: `
Gunung Bromo (dari bahasa Sanskerta: Brahma, salah seorang Dewa Utama dalam agama Hindu) atau dalam bahasa Tengger dieja "Brama", adalah sebuah gunung berapi aktif di Jawa Timur, Indonesia. Gunung ini memiliki ketinggian 2.329 meter di atas permukaan laut dan berada dalam empat wilayah kabupaten, yakni Kabupaten Probolinggo, Kabupaten Pasuruan, Kabupaten Lumajang, dan Kabupaten Malang. Gunung Bromo terkenal sebagai objek wisata utama di Jawa Timur. Sebagai sebuah objek wisata, Bromo menjadi menarik karena statusnya sebagai gunung berapi yang masih aktif. Gunung Bromo termasuk dalam kawasan Taman Nasional Bromo Tengger Semeru.

Bentuk tubuh Gunung Bromo bertautan antara lembah dan ngarai dengan kaldera atau lautan pasir seluas sekitar 10 kilometer persegi.

Gunung Bromo mempunyai sebuah kawah dengan garis tengah ± 800 meter (utara-selatan) dan ± 600 meter (timur-barat). Sedangkan daerah bahayanya berupa lingkaran dengan jari-jari 4 km dari pusat kawah Bromo.

### Wisata Bromo

Perjalanan melalui pintu barat dari arah Pasuruan yaitu masuk dari desa Tosari untuk menuju ke pusat objek wisata (lautan pasir) terbilang berat karena medan yang harus ditempuh tak bisa dilalui oleh kendaraan roda 4 biasa ini dikarenakan jalan turunan dari penanjakan ke arah lautan pasir sangatlah curam, kecuali kita menyewa mobil jeep yang disediakan oleh pengelola wisata, jadi wisatawan banyak yang berjalan kaki untuk menuju ke pusat lokasi. Namun apabila kita melalui pintu utara dari arah sebelum masuk Probolinggo yaitu pada daerah Tongas, kita akan menuju desa Cemoro Lawang sebelum turun menuju lautan pasir maka tidaklah terlalu berat dikarenakan turunan dari lerengnya tidaklah terlalu curam sehingga sepeda motor pun dapat melaluinya. Kebanyakan para wisatawan yang ingin mudah mencapai lautan pasir melewati jalur ini. Namun bila anda ingin menyaksikan matahari terbit yang sering ditampilkan di foto-foto, yang banyak difoto dari puncak penanjakan maka lebih praktis melewati jalur pintu barat.

Namun bila anda mempunyai jiwa petualang maka anda dapat mencoba jalur perjalanan yang jarang dilalui wisatawan. Yaitu melalui kota Malang anda masuk melalui kota kecil tumpang kemudian masuk kota Pronojiwo lalu akan melalui cagar alam yang sangat indah dari sini anda akan menjumpai pertigaan jalan di mana ke arah selatan akan memasuki Ranu Pane (ke arah Gunung Semeru) dan ke arah utara anda memasuki lautan pasir Bromo yang berada di punggung Gunung Bromo sebelah selatan. Pertigaan tersebut bernama Jemplang. Perjalanan diawali dengan menuruni bukit yang kemudian disambut dengan padang rumput yang lama kelamaan berganti menjadi lautan pasir. Jalan ini akan mengitari Gunung Bromo melewati lautan pasir selama kurang lebih 3 jam. Jalur ini sebenarnya tidak terlalu curam dan dapat dilalui sepeda motor, namun memerlukan jiwa petualang karena jalurnya yang masih jarang dilewati dan tidak ada satupun persinggahan maupun rumah penduduk. Kita akan benar- benar disuguhkan dengan perjalanan yang sangat menantang. Namun anda akan diganjar dengan rahasia Bromo yang lain, yang sangat jarang dilihat wisatawan, yaitu padang ruput sabana dan bunga yang sangat luas berada di balik Gunung Bromo. Sungguh pemandangan yang berkebalikan pada sisi utaranya yang gersang dan berdebu. Namun perlu diingat, sebaiknya jangan melalui jalur ini pada malam hari dan atau dalam cuaca yang berkabut. Jalur tidak akan terlihat dalam kondisi seperti ini.

Lautan pasir adalah andalan wisata dari gunung Bromo, di alam pegunungan yang sejuk, kita dapat melihat padang pasir dan rerumputan yang luas. Sedangkan yang paling ditunggu dari Gunung Bromo adalah sightview ketika matahari terbit dan terbenam karena memang akan kelihatan jelas sekali dan sangat indah. Walaupun perjalanan ke Bromo sangat berdebu, tetapi tidak terasa, karena keindahan yang disuguhkan benar-benar luar biasa.

Berlibur menuju Bromo dapat dibilang praktis bila anda menyukai tipe traveller dan melalui jalur pintu utara. Anda dapat melakukan kunjungan dalam jangka waktu 12 jam saja. tentunya bila anda memulainya dari kota Surabaya, Malang, Jember dan sekitarnya. Perjalanan dapat dimulai dari jam 12 malam sehingga anda akan sampai sekitar pukul 2-3 pagi. Di mana anda dapat beristirahat dahulu sebelum melihat matahari terbit. Penjual makanan dan minuman di areal lautan pasir biasanya sudah buka menjelang pukul 3 pagi, sehingga anda sudah bisa bersiap-siap untuk melakukan pendakian melewati anak tangga puncak Bromo yang terkenal itu. nikmatilah pemandangan sampai jam 9 pagi dan anda pun dapat kembali sampai di kota keberangkatan anda sekitar 12 siang. Sebagai catatan, apabila anda melakukan perjalanan di areal lautan pasir di tengah kegelapan malam, sebagai patokan menuju areal parkir sekitar Pura anda dapat melihat patok dari beton yang sengaja diberikan sebagai penunjuk menuju areal pura. Dan apabila anda tersesat jangan panik dan meneruskan perjalanan (apalagi di tengah kabut tebal), tunggulah karena biasanya mulai jam 2-3 pagi beberapa penunggang kuda sewaan melintas di area lautan pasir.
  `,
};
