module.exports = {
  slug: 'madakaripura',
  title: 'Air terjun Madakaripura',
  image: 'https://images.unsplash.com/photo-1506017669510-0bcbe8003d70?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=3300&q=80',
  description: 'Air terjun Madakaripura adalah sebuah air terjun yang terletak di Kabupaten Probolinggo, Provinsi Jawa Timur. Air terjun setinggi 200 meter ini merupakan air terjun tertinggi di Pulau Jawa dan tertinggi kedua di Indonesia.',
  content: `
Perjalanan menuju ke air terjun sangat indah dan memanjakan mata dengan pemandangan pohon-pohon besar, udara yang segar dan juga melewati sungai-sungai. Sepatu yang kuat, tahan air ataupun sandal gunung sangat disarankan untuk perjalanan ini. Perjalanan menempuh kurang lebih 1 jam ketika kemudian Anda merasakan dinginnya sekitar dan juga air yang meloncat-loncat ke tubuh Anda. Maka dari itu, baju ganti, jas hujan ataupun payung sangat disarankan. Anda harus berjalan lebih jauh sedikit untuk bisa menikmati air terjun utamanya. Anda masih harus menaiki tebing yang cukup licin dan sempit. Tapi sekali lagi itu akan terbayar dengan begitu Anda melihat air terjun utama yang berdinging melingkar, jadi terlihat seperti Anda berada di dalam botol. Sangat indah.

Waktu terbaik untuk mengunjungi tempat wisata ini adalah di pagi hari, pasalnya selain cuacanya yang masih sejuk dan masih sepi akan pengunjung, kamu pun mempunyai waktu yang panjang untuk berada di lokasi air terjun. Sebisa mungkin jangan datang di musim penghujan, dikarenakan air terjun utama pada tempat wisata ini memiliki aliran dari sebuah sungai yang dapat sewaktu-waktu berubah volume debit airnya. Namun tak perlu khawatir yang berlebih, pihak pengelola sudah membangun sebuah rumah yang dijaga secara 24 jam, yang bertugas untuk memantau keadaan di sungai tersebut. Bilamana keadaan sedang hujan atau air sedang pasang, maka dengan sigap petugas akan menginformasikan pada petugas yang berada di kawasan air terjun utama, untuk sesegera mungkin mengevakuasi para wisatawan. Hal tersebut mampu meminimalisir bahaya yang tak diinginkan.

Air Terjun Madakaripura dijadikan objek wisata dan dibuka pada tahun 1986. Dengan harga tiket masuk[1] sekitar Rp. 11.000/orang yang dikenakan oleh pihak Perhutani sebesar Rp. 6000/orang serta Dinas Kebudayaan dan Pariwisata Probolinggo sebesar Rp. 5000/orang. Kemudian Anda akan ditawari memakai jasa guide lokal yang juga bisa membawakan tas carrier Anda bila diperlukan, perihal untuk biaya mereka tidak mematok harga, melainkan seikhlasnya dari para wisatawan. Memang demi alasan keamanan, di anjurkan untuk menggunakan jasa guide, mengingat jalur yang akan dilalui dan bahaya akan bebatuan atau batang pohon yang terkadang bisa saja jatuh dari atas lembah.

Bagi wisatawan yang baru pertamakali mengunjungi tempat wisata ini mesti berhati-hati, karena lokasi ini dimanfaatkan oknum-oknum tidak bertanggungjawab. Namun kini keadaannya sudah mulai kondusif. Banyak dari para warga yang berprofesi sebagai guide dan ojek yang mengenakan rompi khusus. Para warga sudah mulai tersadar akan pentingnya kenyamanan para wisatawan yang datang.
`,
};
